# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7caf8579b10248d89428adbbcbc452393b770f16515af4503632167534dcb4de657f3806235702f29a8e5a01101111bddbc7c5649b3f0478c72bb1e365ed9446

test:
  secret_key_base: 02bac164aacd536f5b86d23daa519ce9fb18c0a0f360c0e9120521b09229c056365721bbcb13329bb2a523ffc3444465b78fa80e51c6598579d767d66012ac30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
